spring:
    datasource:
        url: jdbc:mysql://10.tcp.cpolar.top:12060/flowable?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
        username: root
        password: 116190
        driver-class-name: com.mysql.cj.jdbc.Driver
    jackson:
        time-zone: Asia/Shanghai
server:
    port: 3888
